-- Core tables for bot config, markets, positions, orders, trades
CREATE TABLE IF NOT EXISTS bot_config (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  mode VARCHAR(10) NOT NULL DEFAULT 'PAPER',
  candle_unit_min INT NOT NULL DEFAULT 5,
  capital_krw DECIMAL(20,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS market_config (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  market VARCHAR(20) NOT NULL,
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  base_order_krw DECIMAL(20,2) NOT NULL DEFAULT 10000,
  UNIQUE KEY uk_market (market)
);

CREATE TABLE IF NOT EXISTS position (
  market VARCHAR(20) PRIMARY KEY,
  qty DECIMAL(28,12) NOT NULL DEFAULT 0,
  avg_price DECIMAL(28,12) NOT NULL DEFAULT 0,
  add_buys INT NOT NULL DEFAULT 0,
  opened_at TIMESTAMP NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS order_log (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  identifier VARCHAR(64) NOT NULL,
  uuid VARCHAR(64) NULL,
  market VARCHAR(20) NOT NULL,
  side VARCHAR(10) NOT NULL,
  ord_type VARCHAR(20) NOT NULL,
  price DECIMAL(28,12) NULL,
  volume DECIMAL(28,12) NULL,
  state VARCHAR(20) NULL,
  executed_volume DECIMAL(28,12) NULL,
  avg_price DECIMAL(28,12) NULL,
  error_code VARCHAR(64) NULL,
  error_message VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_identifier (identifier),
  KEY idx_market_state (market, state)
);

CREATE TABLE IF NOT EXISTS trade_log (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  ts_epoch_ms BIGINT NOT NULL,
  market VARCHAR(20) NOT NULL,
  action VARCHAR(20) NOT NULL,
  price DECIMAL(28,12) NOT NULL,
  qty DECIMAL(28,12) NOT NULL,
  pnl_krw DECIMAL(20,2) NOT NULL DEFAULT 0,
  roi_percent DECIMAL(10,4) NOT NULL DEFAULT 0,
  mode VARCHAR(10) NOT NULL,
  note VARCHAR(255) NULL,
  KEY idx_ts (ts_epoch_ms),
  KEY idx_market (market)
);
